development:
  adapter: postgresql
  encoding: unicode
  database: elcoding_development
  pool: 5
  #username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: elcoding_test
  pool: 5
  #username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: elcoding_production
  pool: 5
  username: postgresql
  password:
